[package]
name = "lucid-suggest-wasm"
version = "0.5.0"
authors = ["Ilia Schelokov <thaumant@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.58"
lucid-suggest-core = { path = "../core" }

[profile.release]
debug = true
lto = true
opt-level = 's'
