[package]
name = "lucid-suggest"
version = "0.1.0"
authors = ["Ilia Schelokov <thaumant@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
insta = "0.13.1"

[profile.release]
debug = true
lto = true
opt-level = 's'

[dependencies]
wasm-bindgen = "0.2.58"
