[package]
name = "lucid-suggest-core"
version = "0.3.0"
authors = ["Ilia Schelokov <thaumant@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
rust-stemmers = "1.2"

[dev-dependencies]
insta = "0.16"

[profile.release]
